In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv("weatherAUS.csv")
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [ ]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [ ]:
(df["RainTomorrow"]=="Yes").sum()

31877

In [ ]:
(df["RainTomorrow"]=="No").sum()

110316

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Sunshine         69835
Evaporation      62790
Cloud3pm         59358
Cloud9am         55888
Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
Rainfall          3261
RainToday         3261
WindSpeed3pm      3062
Humidity9am       2654
Temp9am           1767
WindSpeed9am      1767
MinTemp           1485
MaxTemp           1261
Location             0
Date                 0
dtype: int64

In [ ]:
print(df.columns)

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df.drop(columns=["Sunshine", "Evaporation", "Cloud3pm", "Cloud9am","Date"], inplace=True,errors="ignore")

In [ ]:
df.head()

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No

In [ ]:
df.shape

(145460, 18)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
RainToday         3261
Rainfall          3261
WindSpeed3pm      3062
Humidity9am       2654
Temp9am           1767
WindSpeed9am      1767
MinTemp           1485
MaxTemp           1261
Location             0
dtype: int64

In [ ]:
df.shape

(145460, 18)

In [ ]:
cat_cols = ['WindGustDir', 'WindDir9am', 'WindDir3pm']
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
nums_cols = ['Pressure9am','Pressure3pm','WindGustSpeed']
df[nums_cols]= df[nums_cols].fillna(df[nums_cols].median())

In [ ]:
df.shape

(145460, 18)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Humidity3pm      4507
Temp3pm          3609
RainTomorrow     3267
RainToday        3261
Rainfall         3261
WindSpeed3pm     3062
Humidity9am      2654
WindSpeed9am     1767
Temp9am          1767
MinTemp          1485
MaxTemp          1261
WindDir9am          0
WindDir3pm          0
WindGustSpeed       0
Pressure9am         0
Pressure3pm         0
WindGustDir         0
Location            0
dtype: int64

In [ ]:
df.shape

(145460, 18)

In [ ]:
df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df = df.dropna(subset=['RainTomorrow'] )

In [ ]:
df.isnull().sum().sort_values(ascending= False)

Humidity3pm      3610
Temp3pm          2726
WindSpeed3pm     2630
Humidity9am      1774
Rainfall         1406
RainToday        1406
WindSpeed9am     1348
Temp9am           904
MinTemp           637
MaxTemp           322
Pressure9am         0
Pressure3pm         0
Location            0
WindDir3pm          0
WindDir9am          0
WindGustSpeed       0
WindGustDir         0
RainTomorrow        0
dtype: int64

In [ ]:
df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df["temp_mean"]= df[["Temp9am","Temp3pm"]].mean(axis=1)
df["windspeed"]= df[["WindSpeed9am","WindSpeed3pm"]].mean(axis=1)
df["humidity_mean"]= df[["Humidity9am","Humidity3pm"]].mean(axis=1)
df["pressure_mean"]= df[["Pressure9am","Pressure3pm"]].mean(axis=1)

df

C:\Users\HP\AppData\Local\Temp\ipykernel_15160\768868931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["temp_mean"]= df[["Temp9am","Temp3pm"]].mean(axis=1)
C:\Users\HP\AppData\Local\Temp\ipykernel_15160\768868931.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["windspeed"]= df[["WindSpeed9am","WindSpeed3pm"]].mean(axis=1)
C:\Users\HP\AppData\Local\Temp\ipykernel_15160\768868931.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["humidity_mean"]= df[["Humidity9am","Humidity3pm"]].mean(axis=1)
C:\Users\HP\AppData\Local\Temp\ipykernel_15160\768868931.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["pressure_mean"]= df[["Pressure9am","Pressure3pm"]].mean(axis=1)

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,temp_mean,windspeed,humidity_mean,pressure_mean
0,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,...,1007.7,1007.1,16.9,21.8,No,No,19.35,22.0,46.5,1007.40
1,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,...,1010.6,1007.8,17.2,24.3,No,No,20.75,13.0,34.5,1009.20
2,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,...,1007.6,1008.7,21.0,23.2,No,No,22.10,22.5,34.0,1008.15
3,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,...,1017.6,1012.8,18.1,26.5,No,No,22.30,10.0,30.5,1015.20
4,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,...,1010.8,1006.0,17.8,29.7,No,No,23.75,13.5,57.5,1008.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,13.0,...,1024.7,1021.2,9.4,20.9,No,No,15.15,14.0,43.0,1022.95
145455,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,...,1024.6,1020.3,10.1,22.4,No,No,16.25,12.0,37.5,1022.45
145456,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,...,1023.5,1019.1,10.9,24.5,No,No,17.70,11.0,38.5,1021.30
145457,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,...,1021.0,1016.8,12.5,26.1,No,No,19.30,9.0,38.5,1018.90
145458,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,...,1019.4,1016.5,15.1,26.0,No,No,20.55,10.0,37.5,1017.95

In [ ]:
df= df.drop(['Temp9am','Temp3pm','Humidity9am','Humidity3pm','Pressure9am','Pressure3pm','WindSpeed9am','WindSpeed3pm','MinTemp','Location','MaxTemp'],axis ='columns')

In [ ]:
df.head()

,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,RainToday,RainTomorrow,temp_mean,windspeed,humidity_mean,pressure_mean
0,0.6,W,44.0,W,WNW,No,No,19.35,22.0,46.5,1007.40
1,0.0,WNW,44.0,NNW,WSW,No,No,20.75,13.0,34.5,1009.20
2,0.0,WSW,46.0,W,WSW,No,No,22.10,22.5,34.0,1008.15
3,0.0,NE,24.0,SE,E,No,No,22.30,10.0,30.5,1015.20
4,1.0,W,41.0,ENE,NW,No,No,23.75,13.5,57.5,1008.40

In [ ]:
df1 = pd.get_dummies(df.RainToday,dtype=int)
df1

        No  Yes
0        1    0
1        1    0
2        1    0
3        1    0
4        1    0
...     ..  ...
145454   1    0
145455   1    0
145456   1    0
145457   1    0
145458   1    0

[142193 rows x 2 columns]

In [ ]:
df3 = pd.get_dummies(df.RainTomorrow,dtype=int)
df3

        No  Yes
0        1    0
1        1    0
2        1    0
3        1    0
4        1    0
...     ..  ...
145454   1    0
145455   1    0
145456   1    0
145457   1    0
145458   1    0

[142193 rows x 2 columns]

In [ ]:
y=df3.drop(['No'],axis=1)
y

        Yes
0         0
1         0
2         0
3         0
4         0
...     ...
145454    0
145455    0
145456    0
145457    0
145458    0

[142193 rows x 1 columns]

In [ ]:
main = pd.concat([df,df1],axis=1)
main

,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,RainToday,RainTomorrow,temp_mean,windspeed,humidity_mean,pressure_mean,No,Yes
0,0.6,W,44.0,W,WNW,No,No,19.35,22.0,46.5,1007.40,1,0
1,0.0,WNW,44.0,NNW,WSW,No,No,20.75,13.0,34.5,1009.20,1,0
2,0.0,WSW,46.0,W,WSW,No,No,22.10,22.5,34.0,1008.15,1,0
3,0.0,NE,24.0,SE,E,No,No,22.30,10.0,30.5,1015.20,1,0
4,1.0,W,41.0,ENE,NW,No,No,23.75,13.5,57.5,1008.40,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.0,E,31.0,ESE,E,No,No,15.15,14.0,43.0,1022.95,1,0
145455,0.0,E,31.0,SE,ENE,No,No,16.25,12.0,37.5,1022.45,1,0
145456,0.0,NNW,22.0,SE,N,No,No,17.70,11.0,38.5,1021.30,1,0
145457,0.0,N,37.0,SE,WNW,No,No,19.30,9.0,38.5,1018.90,1,0
145458,0.0,SE,28.0,SSE,N,No,No,20.55,10.0,37.5,1017.95,1,0

In [ ]:
main1 = main.drop(['RainToday','No','RainTomorrow'],axis=1)
main1.head()

,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,temp_mean,windspeed,humidity_mean,pressure_mean,Yes
0,0.6,W,44.0,W,WNW,19.35,22.0,46.5,1007.40,0
1,0.0,WNW,44.0,NNW,WSW,20.75,13.0,34.5,1009.20,0
2,0.0,WSW,46.0,W,WSW,22.10,22.5,34.0,1008.15,0
3,0.0,NE,24.0,SE,E,22.30,10.0,30.5,1015.20,0
4,1.0,W,41.0,ENE,NW,23.75,13.5,57.5,1008.40,0

In [ ]:
df2 = pd.get_dummies(
    main1,
    columns=[ "WindGustDir", "WindDir9am", "WindDir3pm"],
    drop_first=True,dtype=int
)
df2

,Rainfall,WindGustSpeed,temp_mean,windspeed,humidity_mean,pressure_mean,Yes,WindGustDir_ENE,WindGustDir_ESE,WindGustDir_N,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,0.6,44.0,19.35,22.0,46.5,1007.40,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0.0,44.0,20.75,13.0,34.5,1009.20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0.0,46.0,22.10,22.5,34.0,1008.15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0.0,24.0,22.30,10.0,30.5,1015.20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.0,41.0,23.75,13.5,57.5,1008.40,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.0,31.0,15.15,14.0,43.0,1022.95,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145455,0.0,31.0,16.25,12.0,37.5,1022.45,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145456,0.0,22.0,17.70,11.0,38.5,1021.30,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145457,0.0,37.0,19.30,9.0,38.5,1018.90,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
145458,0.0,28.0,20.55,10.0,37.5,1017.95,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
print(df2.isnull().sum().sum())

3738

In [ ]:
df2 = df2.fillna(df2.median())

In [ ]:
df2.isnull().sum().sort_values(ascending=False)

Rainfall           0
WindGustSpeed      0
WindDir9am_NW      0
WindDir9am_S       0
WindDir9am_SE      0
WindDir9am_SSE     0
WindDir9am_SSW     0
WindDir9am_SW      0
WindDir9am_W       0
WindDir9am_WNW     0
WindDir9am_WSW     0
WindDir3pm_ENE     0
WindDir3pm_ESE     0
WindDir3pm_N       0
WindDir3pm_NE      0
WindDir3pm_NNE     0
WindDir3pm_NNW     0
WindDir3pm_NW      0
WindDir3pm_S       0
WindDir3pm_SE      0
WindDir3pm_SSE     0
WindDir3pm_SSW     0
WindDir3pm_SW      0
WindDir3pm_W       0
WindDir3pm_WNW     0
WindDir9am_NNW     0
WindDir9am_NNE     0
WindDir9am_NE      0
WindGustDir_NNW    0
temp_mean          0
windspeed          0
humidity_mean      0
pressure_mean      0
Yes                0
WindGustDir_ENE    0
WindGustDir_ESE    0
WindGustDir_N      0
WindGustDir_NE     0
WindGustDir_NNE    0
WindGustDir_NW     0
WindDir9am_N       0
WindGustDir_S      0
WindGustDir_SE     0
WindGustDir_SSE    0
WindGustDir_SSW    0
WindGustDir_SW     0
WindGustDir_W      0
WindGustDir_WNW    0
WindGustDir_WSW    0
WindDir9am_ENE     0
WindDir9am_ESE     0
WindDir3pm_WSW     0
dtype: int64

In [ ]:
x=df2
x

,Rainfall,WindGustSpeed,temp_mean,windspeed,humidity_mean,pressure_mean,Yes,WindGustDir_ENE,WindGustDir_ESE,WindGustDir_N,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,0.6,44.0,19.35,22.0,46.5,1007.40,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0.0,44.0,20.75,13.0,34.5,1009.20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0.0,46.0,22.10,22.5,34.0,1008.15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0.0,24.0,22.30,10.0,30.5,1015.20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.0,41.0,23.75,13.5,57.5,1008.40,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.0,31.0,15.15,14.0,43.0,1022.95,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145455,0.0,31.0,16.25,12.0,37.5,1022.45,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145456,0.0,22.0,17.70,11.0,38.5,1021.30,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145457,0.0,37.0,19.30,9.0,38.5,1018.90,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
145458,0.0,28.0,20.55,10.0,37.5,1017.95,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test ,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier( n_estimators=100,random_state=42)
model= model.fit(x,y)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [ ]:
print(x.shape, y.shape)
print((x.index == y.index).all())

(142193, 52) (142193, 1)
True

In [ ]:
model.fit(x_train,y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(random_state=42)

In [ ]:
model.score(x_test,y_test)

0.8378986602904462

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[20936  1162]
 [ 3448  2893]]
              precision    recall  f1-score   support

           0       0.86      0.95      0.90     22098
           1       0.71      0.46      0.56      6341

    accuracy                           0.84     28439
   macro avg       0.79      0.70      0.73     28439
weighted avg       0.83      0.84      0.82     28439